version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: jira-postgres-prod
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - jira-network-prod
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: jira-api-prod
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - jira-network-prod
    restart: unless-stopped
    command: npm run start:prod

volumes:
  postgres_prod_data:

networks:
  jira-network-prod:
    driver: bridge
