version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: project-manager-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-project_manager}
    # Security: Port only exposed to localhost (127.0.0.1)
    # This prevents external access to the database
    ports:
      - "127.0.0.1:${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Security: Use a dedicated network
    networks:
      - project-manager-network

networks:
  project-manager-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
