version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: jira-postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jira_enterprise_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - jira-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jira-api-dev
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - jira-network
    command: npm run start:dev

volumes:
  postgres_dev_data:

networks:
  jira-network:
    driver: bridge
