databaseChangeLog:
  - changeSet:
      id: 001-create-app-user
      author: system
      changes:
        - createTable:
            tableName: app_user
            columns:
              - column:
                  name: id
                  type: BIGSERIAL
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: user_key
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
                    unique: true
              - column:
                  name: username
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
                    unique: true
              - column:
                  name: email
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
                    unique: true
              - column:
                  name: email_lower
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: display_name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: password_hash
                  type: VARCHAR(255)
              - column:
                  name: active
                  type: BOOLEAN
                  defaultValueBoolean: true
              - column:
                  name: created_date
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
              - column:
                  name: updated_date
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
              - column:
                  name: last_login
                  type: TIMESTAMP
              - column:
                  name: avatar_id
                  type: BIGINT

  - changeSet:
      id: 001-create-user-group
      author: system
      changes:
        - createTable:
            tableName: user_group
            columns:
              - column:
                  name: id
                  type: BIGSERIAL
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: group_name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
                    unique: true
              - column:
                  name: description
                  type: TEXT
              - column:
                  name: created_date
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP

  - changeSet:
      id: 001-create-user-group-membership
      author: system
      changes:
        - createTable:
            tableName: user_group_membership
            columns:
              - column:
                  name: id
                  type: BIGSERIAL
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: user_id
                  type: BIGINT
                  constraints:
                    nullable: false
                    foreignKeyName: fk_ugm_user
                    references: app_user(id)
                    deleteCascade: true
              - column:
                  name: group_id
                  type: BIGINT
                  constraints:
                    nullable: false
                    foreignKeyName: fk_ugm_group
                    references: user_group(id)
                    deleteCascade: true
              - column:
                  name: created_date
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP

  - changeSet:
      id: 001-create-user-property
      author: system
      changes:
        - createTable:
            tableName: user_property
            columns:
              - column:
                  name: id
                  type: BIGSERIAL
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: user_id
                  type: BIGINT
                  constraints:
                    nullable: false
                    foreignKeyName: fk_user_property_user
                    references: app_user(id)
                    deleteCascade: true
              - column:
                  name: property_key
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: property_value
                  type: TEXT

  - changeSet:
      id: 001-create-login-info
      author: system
      changes:
        - createTable:
            tableName: login_info
            columns:
              - column:
                  name: id
                  type: BIGSERIAL
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: user_id
                  type: BIGINT
                  constraints:
                    nullable: false
                    foreignKeyName: fk_login_info_user
                    references: app_user(id)
                    deleteCascade: true
              - column:
                  name: login_date
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
              - column:
                  name: ip_address
                  type: VARCHAR(45)
              - column:
                  name: user_agent
                  type: TEXT
              - column:
                  name: success
                  type: BOOLEAN
                  defaultValueBoolean: true
