name: Docker - Build & Publish (Manual)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (leave empty for git SHA)'
        required: false
        default: ''
      latest:
        description: 'Also tag as latest'
        required: true
        default: 'true'
        type: boolean

jobs:
  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine tags
        id: tags
        run: |
          VERSION="${{ github.event.inputs.tag }}"
          if [[ -z "$VERSION" ]]; then
            VERSION="${GITHUB_SHA::8}"
          fi

          TAGS="${{ secrets.DOCKERHUB_USERNAME }}/project-manager:${VERSION}"

          if [[ "${{ github.event.inputs.latest }}" == "true" ]]; then
            TAGS="${TAGS},${{ secrets.DOCKERHUB_USERNAME }}/project-manager:latest"
          fi

          echo "tags=$TAGS" >> $GITHUB_OUTPUT
          echo "Docker tags: $TAGS"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/project-manager:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/project-manager:buildcache,mode=max
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_DATE=${{ github.event.repository.updated_at }}
            VCS_REF=${{ github.sha }}

      - name: Image digest
        run: echo "Image published with digest ${{ steps.docker_build.outputs.digest }}"
